name: barcode_widget
description: >-
  Barcode generation widget for Flutter with support for standard barcodes.
homepage: https://github.com/DavBfr/dart_barcode/tree/master/flutter
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  barcode: ^2.2.0
  flutter: ">=0.14.1"
  mpcore: ">=0.14.1"

dependency_overrides:
  meta: "1.7.0"